## 指定该Eureka实例的端口
#server:
#  port: 8761
#
## 指定该Eureka实例的主机名
#eureka:
#  instance:
#    hostname: discovery
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 高可用
# 指定profile=p1
spring:
  profiles: p1

# 指定该Eureka实例的端口
server:
  port: 8761

# 指定该Eureka实例的主机名
eureka:
  instance:
    hostname: p1 # 指定当profile=p1时，主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://p2:8762/eureka/

spring:
  profiles: p2

server:
  port: 8762

eureka:
  instance:
    hostname: p2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://p1:8761/eureka/